# Generated by Django 4.1.1 on 2022-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=20000)),
                ("description", models.CharField(max_length=20000)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
